/**
 * Summary Agent: Generates clinical visit notes
 */
export function generateVisitSummary(patient, medical, risk, lang = 'hi') {
  const name = medical.patient_name || patient?.name || 'Unknown';
  const age = medical.age || patient?.age || 'N/A';
  const bp = medical.bp_sys && medical.bp_dia ? `${medical.bp_sys}/${medical.bp_dia}` : 'Not measured';
  const wt = medical.weight_kg ? `${medical.weight_kg} kg` : 'Not measured';
  const symptoms = (medical.symptoms || []).length > 0 ? medical.symptoms.join(', ') : 'No symptoms reported';
  
  if (lang === 'hi') {
    return `
📝 विजिट सारांश (${new Date().toLocaleDateString('hi-IN')}):
मरीज़: ${name} (${age} वर्ष)
ब्लड प्रेशर: ${bp}
वजन: ${wt}
लक्षण: ${symptoms}
जोखिम स्तर: ${risk.level.toUpperCase()}
सुझाव: ${risk.protocol}

सखी एआई द्वारा जनरेट किया गया।
    `.trim();
  }

  if (lang === 'kn') {
    return `
📝 ಭೇಟಿ ಸಾರಾಂಶ (${new Date().toLocaleDateString('kn-IN')}):
ರೋಗಿ: ${name} (${age} ವರ್ಷ)
ರಕ್ತದೊತ್ತಡ (BP): ${bp}
ತೂಕ: ${wt}
ಲಕ್ಷಣಗಳು: ${symptoms}
ಅಪಾಯದ ಮಟ್ಟ: ${risk.level.toUpperCase()}
ಸಲಹೆ: ${risk.protocol}

ಸಖಿ ಎಐ ನಿಂದ ರಚಿಸಲಾಗಿದೆ.
    `.trim();
  }

  return `
📝 Visit Summary (${new Date().toLocaleDateString()}):
Patient: ${name} (${age} yrs)
BP: ${bp}
Weight: ${wt}
Symptoms: ${symptoms}
Risk: ${risk.level.toUpperCase()}
Protocol: ${risk.protocol}

Generated by Sakhi AI.
  `.trim();
}
